apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-vol
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory_mebibyte }}Mi
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory_mebibyte }}Mi