apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "9093"
    prometheus.io/path: '/metrics'
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    component: core
    statefulset.kubernetes.io/pod-name: prometheus-0
  annotations:
    prometheus.io/scrape: 'true'
spec:
  clusterIP: None
  ports:
    - name: prometheus
      port: 10060
  selector:
    app: prometheus
    component: core
